import "@/styles/globals.css";
import {ReactNode} from "react";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {ChakraUIProvider} from "@/lib/chakraUI";
import {NextAuthProvider} from "@/lib/nextauth";
import {ApolloGraphQLProvider} from "@/lib/graphql/apollo/apollo-client";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "ChatifyX",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ApolloGraphQLProvider>
            <NextAuthProvider>
                <ChakraUIProvider>
                    {children}
                </ChakraUIProvider>
            </NextAuthProvider>
        </ApolloGraphQLProvider>
        </body>
        </html>
    );
}
